// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (user_id) VALUES ($1) RETURNING id, created_at
`

type CreateRequestRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateRequest(ctx context.Context, userID uuid.UUID) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest, userID)
	var i CreateRequestRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getAllRequests = `-- name: GetAllRequests :many
SELECT id, user_id, status, comment, created_at, processed_at, processed_by FROM requests ORDER BY created_at DESC, id DESC
`

func (q *Queries) GetAllRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.Query(ctx, getAllRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProcessedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequest = `-- name: GetRequest :one
SELECT id, user_id, status, comment, created_at, processed_at, processed_by FROM requests WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id int64) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ProcessedBy,
	)
	return i, err
}

const getRequestsByStatus = `-- name: GetRequestsByStatus :many
SELECT id, user_id, status, comment, created_at, processed_at, processed_by FROM requests WHERE status = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) GetRequestsByStatus(ctx context.Context, status RequestStatus) ([]Request, error) {
	rows, err := q.db.Query(ctx, getRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProcessedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestsByUser = `-- name: GetRequestsByUser :many
SELECT id, user_id, status, comment, created_at, processed_at, processed_by FROM requests WHERE user_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) GetRequestsByUser(ctx context.Context, userID uuid.UUID) ([]Request, error) {
	rows, err := q.db.Query(ctx, getRequestsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProcessedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processRequest = `-- name: ProcessRequest :execresult
UPDATE requests
SET status = $2, comment = $3, processed_at = $4, processed_by = $5
WHERE id = $1 AND status = 'new'
`

type ProcessRequestParams struct {
	ID          int64
	Status      RequestStatus
	Comment     string
	ProcessedAt *time.Time
	ProcessedBy *uuid.UUID
}

func (q *Queries) ProcessRequest(ctx context.Context, arg ProcessRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, processRequest,
		arg.ID,
		arg.Status,
		arg.Comment,
		arg.ProcessedAt,
		arg.ProcessedBy,
	)
}
