// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (id, login, password_hash, role, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (login) DO NOTHING
`

type CreateUserParams struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	Role         UserRole
	CreatedAt    time.Time
}

// 0 затронутых строк — логин занят (ErrLoginTaken).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, password_hash, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, role, created_at FROM users WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
