// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveBooking = `-- name: ApproveBooking :execresult
INSERT INTO bookings (service_id, date, request_id) VALUES ($2, $3, $1) ON CONFLICT DO NOTHING
`

type ApproveBookingParams struct {
	RequestID int64
	ServiceID string
	Date      pgtype.Date
}

func (q *Queries) ApproveBooking(ctx context.Context, arg ApproveBookingParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, approveBooking, arg.RequestID, arg.ServiceID, arg.Date)
}

const cancelBooking = `-- name: CancelBooking :execresult
DELETE FROM bookings WHERE request_id = $1
`

func (q *Queries) CancelBooking(ctx context.Context, requestID int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelBooking, requestID)
}

const checkServiceAvailability = `-- name: CheckServiceAvailability :one
SELECT 1 FROM bookings WHERE service_id = $1 AND date = $2
`

type CheckServiceAvailabilityParams struct {
	ServiceID string
	Date      pgtype.Date
}

func (q *Queries) CheckServiceAvailability(ctx context.Context, arg CheckServiceAvailabilityParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkServiceAvailability, arg.ServiceID, arg.Date)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
