// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddItemsToRequestParams struct {
	RequestID int64
	ServiceID string
	Date      pgtype.Date
}

const getRequestInfo = `-- name: GetRequestInfo :many
SELECT services.name, services.kind, date FROM request_items INNER JOIN services ON services.id = service_id WHERE request_id = $1
`

type GetRequestInfoRow struct {
	Name string
	Kind string
	Date pgtype.Date
}

func (q *Queries) GetRequestInfo(ctx context.Context, requestID int64) ([]GetRequestInfoRow, error) {
	rows, err := q.db.Query(ctx, getRequestInfo, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequestInfoRow
	for rows.Next() {
		var i GetRequestInfoRow
		if err := rows.Scan(&i.Name, &i.Kind, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
