// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ServiceID string
	Date      pgtype.Date
	RequestID int64
}

type Request struct {
	ID              int64
	UserLogin       string
	Status          string
	Comment         string
	ResponseComment string
	CreatedAt       pgtype.Timestamptz
	ProcessedAt     pgtype.Timestamptz
	ProcessedBy     *string
}

type RequestItem struct {
	RequestID int64
	ServiceID string
	Date      pgtype.Date
}

type Service struct {
	ID     string
	Name   string
	Kind   string
	Active bool
}

type User struct {
	Login        string
	Name         string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
