// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const cancelRequest = `-- name: CancelRequest :execresult
UPDATE requests SET status = 'cancelled' WHERE id = $1 AND user_login = $2
`

type CancelRequestParams struct {
	ID        int64
	UserLogin string
}

func (q *Queries) CancelRequest(ctx context.Context, arg CancelRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelRequest, arg.ID, arg.UserLogin)
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (user_login) VALUES ($1) RETURNING id
`

func (q *Queries) CreateRequest(ctx context.Context, userLogin string) (int64, error) {
	row := q.db.QueryRow(ctx, createRequest, userLogin)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllRequests = `-- name: GetAllRequests :many
SELECT id, user_login, status, comment, response_comment, created_at, processed_at, processed_by FROM requests
`

func (q *Queries) GetAllRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.Query(ctx, getAllRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserLogin,
			&i.Status,
			&i.Comment,
			&i.ResponseComment,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProcessedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestsByStatus = `-- name: GetRequestsByStatus :many
SELECT id, user_login, status, comment, response_comment, created_at, processed_at, processed_by FROM requests WHERE status = $1
`

func (q *Queries) GetRequestsByStatus(ctx context.Context, status string) ([]Request, error) {
	rows, err := q.db.Query(ctx, getRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserLogin,
			&i.Status,
			&i.Comment,
			&i.ResponseComment,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProcessedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processRequest = `-- name: ProcessRequest :execresult
UPDATE requests SET status = $2, response_comment = $3, processed_at = NOW(), processed_by = $4 WHERE id = $1
`

type ProcessRequestParams struct {
	ID              int64
	Status          string
	ResponseComment string
	ProcessedBy     *string
}

func (q *Queries) ProcessRequest(ctx context.Context, arg ProcessRequestParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, processRequest,
		arg.ID,
		arg.Status,
		arg.ResponseComment,
		arg.ProcessedBy,
	)
}
