// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createService = `-- name: CreateService :execresult
INSERT INTO services (id, name, kind, active) VALUES ($1, $2, $3, $4)
`

type CreateServiceParams struct {
	ID     string
	Name   string
	Kind   string
	Active bool
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createService,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Active,
	)
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, kind, active FROM services
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServicesByKind = `-- name: GetServicesByKind :many
SELECT id, name, kind, active FROM services WHERE kind = $1
`

func (q *Queries) GetServicesByKind(ctx context.Context, kind string) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServicesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchForService = `-- name: SearchForService :many
SELECT id, name, kind, active FROM services WHERE name LIKE $1
`

func (q *Queries) SearchForService(ctx context.Context, name string) ([]Service, error) {
	rows, err := q.db.Query(ctx, searchForService, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceStatus = `-- name: SetServiceStatus :execresult
UPDATE services SET active = $2 WHERE id = $1
`

type SetServiceStatusParams struct {
	ID     string
	Active bool
}

func (q *Queries) SetServiceStatus(ctx context.Context, arg SetServiceStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setServiceStatus, arg.ID, arg.Active)
}
