// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkPassword = `-- name: CheckPassword :one
SELECT 1 FROM users WHERE login = $1 AND password_hash = $2
`

type CheckPasswordParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) CheckPassword(ctx context.Context, arg CheckPasswordParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkPassword, arg.Login, arg.PasswordHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (login, name, password_hash, role) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING
`

type CreateUserParams struct {
	Login        string
	Name         string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createUser,
		arg.Login,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
	)
}

const getInfoByLogin = `-- name: GetInfoByLogin :one
SELECT name,role,created_at FROM users WHERE login = $1
`

type GetInfoByLoginRow struct {
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetInfoByLogin(ctx context.Context, login string) (GetInfoByLoginRow, error) {
	row := q.db.QueryRow(ctx, getInfoByLogin, login)
	var i GetInfoByLoginRow
	err := row.Scan(&i.Name, &i.Role, &i.CreatedAt)
	return i, err
}
