// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"booking/internal/domain/booking"
	"booking/internal/domain/cart"
	"booking/internal/domain/service"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRedis creates a new instance of Redis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *Redis {
	mock := &Redis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Redis is an autogenerated mock type for the Redis type
type Redis struct {
	mock.Mock
}

type Redis_Expecter struct {
	mock *mock.Mock
}

func (_m *Redis) EXPECT() *Redis_Expecter {
	return &Redis_Expecter{mock: &_m.Mock}
}

// DeleteCart provides a mock function for the type Redis
func (_mock *Redis) DeleteCart(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_DeleteCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCart'
type Redis_DeleteCart_Call struct {
	*mock.Call
}

// DeleteCart is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Redis_Expecter) DeleteCart(ctx interface{}, userID interface{}) *Redis_DeleteCart_Call {
	return &Redis_DeleteCart_Call{Call: _e.mock.On("DeleteCart", ctx, userID)}
}

func (_c *Redis_DeleteCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Redis_DeleteCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Redis_DeleteCart_Call) Return(err error) *Redis_DeleteCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_DeleteCart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *Redis_DeleteCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function for the type Redis
func (_mock *Redis) GetCart(ctx context.Context, userID uuid.UUID) (*cart.Cart, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *cart.Cart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*cart.Cart, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *cart.Cart); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Redis_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type Redis_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Redis_Expecter) GetCart(ctx interface{}, userID interface{}) *Redis_GetCart_Call {
	return &Redis_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *Redis_GetCart_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Redis_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Redis_GetCart_Call) Return(cart1 *cart.Cart, err error) *Redis_GetCart_Call {
	_c.Call.Return(cart1, err)
	return _c
}

func (_c *Redis_GetCart_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*cart.Cart, error)) *Redis_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetCartTTL provides a mock function for the type Redis
func (_mock *Redis) GetCartTTL(ctx context.Context, userID uuid.UUID) (time.Duration, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCartTTL")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (time.Duration, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) time.Duration); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Redis_GetCartTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCartTTL'
type Redis_GetCartTTL_Call struct {
	*mock.Call
}

// GetCartTTL is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *Redis_Expecter) GetCartTTL(ctx interface{}, userID interface{}) *Redis_GetCartTTL_Call {
	return &Redis_GetCartTTL_Call{Call: _e.mock.On("GetCartTTL", ctx, userID)}
}

func (_c *Redis_GetCartTTL_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Redis_GetCartTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Redis_GetCartTTL_Call) Return(duration time.Duration, err error) *Redis_GetCartTTL_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *Redis_GetCartTTL_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (time.Duration, error)) *Redis_GetCartTTL_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCartItem provides a mock function for the type Redis
func (_mock *Redis) RemoveCartItem(ctx context.Context, userID uuid.UUID, item cart.Item) error {
	ret := _mock.Called(ctx, userID, item)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCartItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, cart.Item) error); ok {
		r0 = returnFunc(ctx, userID, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_RemoveCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCartItem'
type Redis_RemoveCartItem_Call struct {
	*mock.Call
}

// RemoveCartItem is a helper method to define mock.On call
//   - ctx
//   - userID
//   - item
func (_e *Redis_Expecter) RemoveCartItem(ctx interface{}, userID interface{}, item interface{}) *Redis_RemoveCartItem_Call {
	return &Redis_RemoveCartItem_Call{Call: _e.mock.On("RemoveCartItem", ctx, userID, item)}
}

func (_c *Redis_RemoveCartItem_Call) Run(run func(ctx context.Context, userID uuid.UUID, item cart.Item)) *Redis_RemoveCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(cart.Item))
	})
	return _c
}

func (_c *Redis_RemoveCartItem_Call) Return(err error) *Redis_RemoveCartItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_RemoveCartItem_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, item cart.Item) error) *Redis_RemoveCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCart provides a mock function for the type Redis
func (_mock *Redis) SaveCart(ctx context.Context, c *cart.Cart) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for SaveCart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cart.Cart) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Redis_SaveCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCart'
type Redis_SaveCart_Call struct {
	*mock.Call
}

// SaveCart is a helper method to define mock.On call
//   - ctx
//   - c
func (_e *Redis_Expecter) SaveCart(ctx interface{}, c interface{}) *Redis_SaveCart_Call {
	return &Redis_SaveCart_Call{Call: _e.mock.On("SaveCart", ctx, c)}
}

func (_c *Redis_SaveCart_Call) Run(run func(ctx context.Context, c *cart.Cart)) *Redis_SaveCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*cart.Cart))
	})
	return _c
}

func (_c *Redis_SaveCart_Call) Return(err error) *Redis_SaveCart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Redis_SaveCart_Call) RunAndReturn(run func(ctx context.Context, c *cart.Cart) error) *Redis_SaveCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostgres creates a new instance of Postgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *Postgres {
	mock := &Postgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Postgres is an autogenerated mock type for the Postgres type
type Postgres struct {
	mock.Mock
}

type Postgres_Expecter struct {
	mock *mock.Mock
}

func (_m *Postgres) EXPECT() *Postgres_Expecter {
	return &Postgres_Expecter{mock: &_m.Mock}
}

// GetBookings provides a mock function for the type Postgres
func (_mock *Postgres) GetBookings(ctx context.Context, date service.Date) ([]booking.Booking, error) {
	ret := _mock.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for GetBookings")
	}

	var r0 []booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.Date) ([]booking.Booking, error)); ok {
		return returnFunc(ctx, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, service.Date) []booking.Booking); ok {
		r0 = returnFunc(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, service.Date) error); ok {
		r1 = returnFunc(ctx, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_GetBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookings'
type Postgres_GetBookings_Call struct {
	*mock.Call
}

// GetBookings is a helper method to define mock.On call
//   - ctx
//   - date
func (_e *Postgres_Expecter) GetBookings(ctx interface{}, date interface{}) *Postgres_GetBookings_Call {
	return &Postgres_GetBookings_Call{Call: _e.mock.On("GetBookings", ctx, date)}
}

func (_c *Postgres_GetBookings_Call) Run(run func(ctx context.Context, date service.Date)) *Postgres_GetBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.Date))
	})
	return _c
}

func (_c *Postgres_GetBookings_Call) Return(bookings []booking.Booking, err error) *Postgres_GetBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *Postgres_GetBookings_Call) RunAndReturn(run func(ctx context.Context, date service.Date) ([]booking.Booking, error)) *Postgres_GetBookings_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type Postgres
func (_mock *Postgres) GetService(ctx context.Context, id string) (*service.Service, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 *service.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.Service, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.Service); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type Postgres_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *Postgres_Expecter) GetService(ctx interface{}, id interface{}) *Postgres_GetService_Call {
	return &Postgres_GetService_Call{Call: _e.mock.On("GetService", ctx, id)}
}

func (_c *Postgres_GetService_Call) Run(run func(ctx context.Context, id string)) *Postgres_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Postgres_GetService_Call) Return(service1 *service.Service, err error) *Postgres_GetService_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *Postgres_GetService_Call) RunAndReturn(run func(ctx context.Context, id string) (*service.Service, error)) *Postgres_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetServices provides a mock function for the type Postgres
func (_mock *Postgres) GetServices(ctx context.Context) ([]*service.Service, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetServices")
	}

	var r0 []*service.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*service.Service, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*service.Service); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*service.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Postgres_GetServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServices'
type Postgres_GetServices_Call struct {
	*mock.Call
}

// GetServices is a helper method to define mock.On call
//   - ctx
func (_e *Postgres_Expecter) GetServices(ctx interface{}) *Postgres_GetServices_Call {
	return &Postgres_GetServices_Call{Call: _e.mock.On("GetServices", ctx)}
}

func (_c *Postgres_GetServices_Call) Run(run func(ctx context.Context)) *Postgres_GetServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Postgres_GetServices_Call) Return(services []*service.Service, err error) *Postgres_GetServices_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *Postgres_GetServices_Call) RunAndReturn(run func(ctx context.Context) ([]*service.Service, error)) *Postgres_GetServices_Call {
	_c.Call.Return(run)
	return _c
}
