// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"
	"time"
)

const createBookingsForRequest = `-- name: CreateBookingsForRequest :exec
INSERT INTO bookings (service_id, date, request_id)
SELECT service_id, date, request_id FROM request_items WHERE request_items.request_id = $1
`

func (q *Queries) CreateBookingsForRequest(ctx context.Context, requestID int64) error {
	_, err := q.db.Exec(ctx, createBookingsForRequest, requestID)
	return err
}

const getBookingsByDate = `-- name: GetBookingsByDate :many
SELECT service_id, date, request_id FROM bookings WHERE date = $1 ORDER BY service_id
`

func (q *Queries) GetBookingsByDate(ctx context.Context, date time.Time) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(&i.ServiceID, &i.Date, &i.RequestID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isServiceBooked = `-- name: IsServiceBooked :one
SELECT EXISTS (SELECT 1 FROM bookings WHERE service_id = $1 AND date = $2)
`

type IsServiceBookedParams struct {
	ServiceID string
	Date      time.Time
}

func (q *Queries) IsServiceBooked(ctx context.Context, arg IsServiceBookedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isServiceBooked, arg.ServiceID, arg.Date)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
