// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForAddItemsToRequest implements pgx.CopyFromSource.
type iteratorForAddItemsToRequest struct {
	rows                 []AddItemsToRequestParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddItemsToRequest) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddItemsToRequest) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RequestID,
		r.rows[0].ServiceID,
		r.rows[0].Date,
	}, nil
}

func (r iteratorForAddItemsToRequest) Err() error {
	return nil
}

func (q *Queries) AddItemsToRequest(ctx context.Context, arg []AddItemsToRequestParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"request_items"}, []string{"request_id", "service_id", "date"}, &iteratorForAddItemsToRequest{rows: arg})
}
