// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"
	"time"
)

type AddItemsToRequestParams struct {
	RequestID int64
	ServiceID string
	Date      time.Time
}

const getRequestInfo = `-- name: GetRequestInfo :many
SELECT services.name, services.kind, date FROM request_items INNER JOIN services ON services.id = service_id WHERE request_id = $1
`

type GetRequestInfoRow struct {
	Name string
	Kind ServiceKind
	Date time.Time
}

func (q *Queries) GetRequestInfo(ctx context.Context, requestID int64) ([]GetRequestInfoRow, error) {
	rows, err := q.db.Query(ctx, getRequestInfo, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequestInfoRow
	for rows.Next() {
		var i GetRequestInfoRow
		if err := rows.Scan(&i.Name, &i.Kind, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestItems = `-- name: GetRequestItems :many
SELECT request_id, service_id, date FROM request_items
WHERE request_id = ANY($1::bigint[])
ORDER BY request_id, date, service_id
`

func (q *Queries) GetRequestItems(ctx context.Context, requestIds []int64) ([]RequestItem, error) {
	rows, err := q.db.Query(ctx, getRequestItems, requestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestItem
	for rows.Next() {
		var i RequestItem
		if err := rows.Scan(&i.RequestID, &i.ServiceID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
