// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type RequestStatus string

const (
	RequestStatusNew       RequestStatus = "new"
	RequestStatusApproved  RequestStatus = "approved"
	RequestStatusRejected  RequestStatus = "rejected"
	RequestStatusCancelled RequestStatus = "cancelled"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus
	Valid         bool // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type ServiceKind string

const (
	ServiceKindRoom      ServiceKind = "room"
	ServiceKindLab       ServiceKind = "lab"
	ServiceKindEquipment ServiceKind = "equipment"
)

func (e *ServiceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceKind(s)
	case string:
		*e = ServiceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceKind: %T", src)
	}
	return nil
}

type NullServiceKind struct {
	ServiceKind ServiceKind
	Valid       bool // Valid is true if ServiceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceKind) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceKind), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Booking struct {
	ServiceID string
	Date      time.Time
	RequestID int64
}

type Request struct {
	ID          int64
	UserID      uuid.UUID
	Status      RequestStatus
	Comment     string
	CreatedAt   time.Time
	ProcessedAt *time.Time
	ProcessedBy *uuid.UUID
}

type RequestItem struct {
	RequestID int64
	ServiceID string
	Date      time.Time
}

type Service struct {
	ID     string
	Name   string
	Kind   ServiceKind
	Active bool
}

type User struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	Role         UserRole
	CreatedAt    time.Time
}
