// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createService = `-- name: CreateService :execresult
INSERT INTO services (id, name, kind, active) VALUES ($1, $2, $3, $4)
`

type CreateServiceParams struct {
	ID     string
	Name   string
	Kind   ServiceKind
	Active bool
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createService,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Active,
	)
}

const getAllServices = `-- name: GetAllServices :many
SELECT id, name, kind, active FROM services ORDER BY id
`

func (q *Queries) GetAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getService = `-- name: GetService :one
SELECT id, name, kind, active FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Active,
	)
	return i, err
}

const getServicesByKind = `-- name: GetServicesByKind :many
SELECT id, name, kind, active FROM services WHERE kind = $1 ORDER BY id
`

func (q *Queries) GetServicesByKind(ctx context.Context, kind ServiceKind) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServicesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchForService = `-- name: SearchForService :many
SELECT id, name, kind, active FROM services WHERE name ILIKE '%' || $1::text || '%' ORDER BY id
`

// Подстрока без учёта регистра; % и _ в запросе считаются шаблоном LIKE.
func (q *Queries) SearchForService(ctx context.Context, query string) ([]Service, error) {
	rows, err := q.db.Query(ctx, searchForService, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceStatus = `-- name: SetServiceStatus :execresult
UPDATE services SET active = $2 WHERE id = $1
`

type SetServiceStatusParams struct {
	ID     string
	Active bool
}

func (q *Queries) SetServiceStatus(ctx context.Context, arg SetServiceStatusParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, setServiceStatus, arg.ID, arg.Active)
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO services (id, name, kind, active) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name, kind = EXCLUDED.kind, active = EXCLUDED.active
`

type UpsertServiceParams struct {
	ID     string
	Name   string
	Kind   ServiceKind
	Active bool
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.Exec(ctx, upsertService,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Active,
	)
	return err
}
